"""Add video fields and progress tracking

Revision ID: 093aa7e00a60
Revises: 805bc3415044
Create Date: 2025-11-26 17:26:16.046187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""Add video fields and progress tracking

Revision ID: 093aa7e00a60
Revises: 805bc3415044
Create Date: 2025-11-26 17:26:16.046187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093aa7e00a60'
down_revision: Union[str, Sequence[str], None] = '805bc3415044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('movies', sa.Column('video_source', sa.String(length=20), nullable=True))
    op.add_column('movies', sa.Column('is_free', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('watchlist', sa.Column('progress_seconds', sa.Integer(), nullable=True))
    op.add_column('watchlist', sa.Column('total_duration_seconds', sa.Integer(), nullable=True))
    op.add_column('watchlist', sa.Column('last_watched_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist', 'last_watched_at')
    op.drop_column('watchlist', 'total_duration_seconds')
    op.drop_column('watchlist', 'progress_seconds')
    op.drop_column('movies', 'is_free')
    op.drop_column('movies', 'video_source')
    op.drop_column('movies', 'video_url')
    # ### end Alembic commands ###
