"""add_review_votes_table

Revision ID: 40c9f7984489
Revises: bf44fe1f7001
Create Date: 2025-11-24 07:03:02.071474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c9f7984489'
down_revision: Union[str, Sequence[str], None] = 'bf44fe1f7001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('vote_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'review_id', name='uq_review_vote_user_review')
    )
    op.create_index(op.f('ix_review_votes_external_id'), 'review_votes', ['external_id'], unique=True)
    op.add_column('users', sa.Column('banner_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banner_url')
    op.drop_index(op.f('ix_review_votes_external_id'), table_name='review_votes')
    op.drop_table('review_votes')
    # ### end Alembic commands ###
