"""Add review comments and likes

Revision ID: 8aee1c2386fc
Revises: 659988564962
Create Date: 2025-11-24 15:12:58.805921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8aee1c2386fc'
down_revision: Union[str, Sequence[str], None] = '659988564962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_comment_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['review_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'comment_id', name='uq_review_comment_like_user_comment')
    )
    op.create_index(op.f('ix_review_comment_likes_external_id'), 'review_comment_likes', ['external_id'], unique=True)
    op.add_column('review_comments', sa.Column('external_id', sa.String(length=50), nullable=False))
    op.add_column('review_comments', sa.Column('edited_at', sa.DateTime(), nullable=True))
    op.add_column('review_comments', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('review_comments', sa.Column('likes_count', sa.Integer(), nullable=False))
    op.add_column('review_comments', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_review_comments_external_id'), 'review_comments', ['external_id'], unique=True)
    op.create_foreign_key(None, 'review_comments', 'review_comments', ['parent_id'], ['id'])
    op.drop_column('review_comments', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_comments', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'review_comments', type_='foreignkey')
    op.drop_index(op.f('ix_review_comments_external_id'), table_name='review_comments')
    op.drop_column('review_comments', 'parent_id')
    op.drop_column('review_comments', 'likes_count')
    op.drop_column('review_comments', 'is_deleted')
    op.drop_column('review_comments', 'edited_at')
    op.drop_column('review_comments', 'external_id')
    op.drop_index(op.f('ix_review_comment_likes_external_id'), table_name='review_comment_likes')
    op.drop_table('review_comment_likes')
    # ### end Alembic commands ###
