"""Remove like_count from PulseBookmark

Revision ID: 982c56c4934d
Revises: eb02a63d64d9
Create Date: 2025-11-23 09:04:11.917845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982c56c4934d'
down_revision: Union[str, Sequence[str], None] = 'eb02a63d64d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pulse_bookmarks', 'like_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pulse_bookmarks', sa.Column('like_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
