"""add_gif_url_to_reviews

Revision ID: bf44fe1f7001
Revises: 982c56c4934d
Create Date: 2025-11-23 10:03:24.026254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf44fe1f7001'
down_revision: Union[str, Sequence[str], None] = '982c56c4934d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('gif_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'gif_url')
    # ### end Alembic commands ###
