"""Add PulseBookmark

Revision ID: eb02a63d64d9
Revises: 58172f66d20a
Create Date: 2025-11-23 09:00:56.177148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb02a63d64d9'
down_revision: Union[str, Sequence[str], None] = '58172f66d20a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pulse_bookmarks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pulse_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pulse_id'], ['pulses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pulse_id', name='uq_pulse_bookmark_user_pulse')
    )
    op.drop_column('pulse_comments', 'like_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pulse_comments', sa.Column('like_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('pulse_bookmarks')
    # ### end Alembic commands ###
